<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:schema="http://glendale.org.uk/worldgen/ws/schemas"
                  xmlns:tns="http://glendale.org.uk/worldgen/ws/definitions"
                  targetNamespace="http://glendale.org.uk/worldgen/ws/definitions">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://glendale.org.uk/worldgen/ws"
                schemaLocation="ships.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="ShipInfoRequest">                                                 
        <wsdl:part element="schema:ShipRequest" name="ShipRequest"/>               
    </wsdl:message>

    <wsdl:message name="ShipInfoResponse">                                                 
        <wsdl:part element="schema:ShipResponse" name="ShipResponse"/>               
    </wsdl:message>
    
    <wsdl:portType name="ShipResource">                                                 
        <wsdl:operation name="getShip">
            <wsdl:input message="tns:ShipInfoRequest" name="ShipRequest"/>
            <wsdl:output message="tns:ShipInfoResponse" name="ShipResponse"/>             
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="ShipBinding" type="tns:ShipResource">                
        <soap:binding style="document"                                                  
            transport="http://schemas.xmlsoap.org/soap/http"/>     
                              
        <wsdl:operation name="getShip">
            <soap:operation soapAction="http://glendale.org.uk/worldgen/ws/ship/get"/>         
            <wsdl:input name="ShipInfoRequest">
                <soap:body use="literal"/>                                          
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="ShipService">
        <wsdl:port binding="tns:ShipBinding" name="ShipPort">       
            <soap:address location="http://localhost:8080/shipService/"/>        
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
