#!/bin/sh

cd $1/medium
for dir in xxsmall xsmall small large xlarge xxlarge
do
	h=`grep icon.height ../$dir/icons.properties | awk '{print $2; }'`
	w=`grep icon.width ../$dir/icons.properties | awk '{print $2; }'`

	geom=${w}x${h}
	echo $geom

	for img in *.png
	do
		convert -scale $geom $img ../$dir/$img
	done

	for sub in features places hills
	do
		if [ -d $sub ]
		then
			for img in $sub/*.png
			do
				convert -scale $geom $img ../$dir/$img
			done
		fi
	done

done
