/*
 * Copyright (C) 2011 Samuel Penn, sam@glendale.org.uk
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2.
 * See the file COPYING.
 */
package uk.org.glendale.worldgen.civ.commodity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Maps an action to a commodity type. Used when producing resources from other
 * types of resources. For example, 'Grasses' might map to 'Grain' when
 * 'Farming' (AgFa) is applied.
 * 
 * @author Samuel Penn
 */
@Entity
@Table(name = "commodity_map")
public class CommodityMap {
	@Id
	@GeneratedValue
	@Column(name = "id")
	private int id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commodity_id", nullable = false)
	private Commodity commodity;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "output_id", nullable = false)
	private Commodity output;

	@Column(name = "mode")
	private String operation;

	@Column(name = "efficiency")
	private int efficiency;

	private CommodityMap() {
		// Private empty constructor for JPA.
	}

	/**
	 * Instantiate a map between a commodity and its output. The operation is
	 * the process which creates the output. Efficiency is assumed to be 100%.
	 * 
	 * @param commodity
	 *            Commodity map is for.
	 * @param output
	 *            Output generated.
	 * @param operation
	 *            Operation that must be performed.
	 */
	CommodityMap(Commodity commodity, Commodity output, String operation) {
		this.commodity = commodity;
		this.output = output;
		this.operation = operation;
		this.efficiency = 100;
	}

	/**
	 * Instantiate a map between a commodity and its output. The operation is
	 * the process which creates the output. The efficiency is a percentage
	 * which defines how well the process works, and modifies the production
	 * rating of the output.
	 * 
	 * @param commodity
	 *            Commodity map is for.
	 * @param output
	 *            Output generated.
	 * @param operation
	 *            Operation that must be performed.
	 * @param effiency
	 *            Percentage.
	 */
	CommodityMap(Commodity commodity, Commodity output, String operation,
			int efficiency) {
		this.commodity = commodity;
		this.output = output;
		this.operation = operation;
		this.efficiency = efficiency;
	}

	/**
	 * Gets the the commodity that this mapping is for.
	 * 
	 * @return Base commodity.
	 */
	public Commodity getCommodity() {
		return commodity;
	}

	/**
	 * Gets the output that is generated by this commodity when the operation is
	 * performed.
	 * 
	 * @return Output commodity.
	 */
	public Commodity getOutput() {
		return output;
	}

	/**
	 * Gets the operation that produces the output. This will be one or more
	 * space separated operations.
	 * 
	 * @return One or more operations.
	 */
	public String getOperation() {
		return operation;
	}

	/**
	 * Gets the efficiency of the output generation. Defaults to 100% if it
	 * wasn't set.
	 * 
	 * @return Efficiency as a percentage.
	 */
	public int getEfficiency() {
		return efficiency;
	}
}
